### ISSUE TITLE
OSError: [Errno 6] No such device or address 

### ISSUE THREAD

**Issue by manoflinux** [TeaM-TL/FotoKilof#119]
**Describe the bug**
I get OSError: [Errno 6] No such device or address 

**To Reproduce**
running it on the command line with no arguments

**Expected behavior**
I expected a window to open

**Screenshots**
fotokilof
Traceback (most recent call last):
  File "/home/sysop/.local/bin/fotokilof", line 6, in <module>
    from src import __main__
  File "/home/sysop/.local/lib/python3.7/site-packages/src/__main__.py", line 2371, in <module>
    GM_or_IM_data = magick.check_magick()
  File "/home/sysop/.local/lib/python3.7/site-packages/src/magick.py", line 240, in check_magick
    version = version + ':' + get_magick_version(result_gm)
  File "/home/sysop/.local/lib/python3.7/site-packages/src/magick.py", line 196, in get_magick_version
    os.getlogin() + "_version"))
OSError: [Errno 6] No such device or address

**Desktop (please complete the following information):**
debian based
chrome
100

**Smartphone (please complete the following information):**

**Additional context**
I got this error first as described in https://github.com/TeaM-TL/FotoKilof/issues/116 and fixed it with a pillow upgrade, just in case they are related.
  fotokilof
Traceback (most recent call last):
  File "/home/sysop/.local/bin/fotokilof", line 6, in <module>
    from src import __main__
  File "/home/sysop/.local/lib/python3.7/site-packages/src/__main__.py", line 48, in <module>
    from PIL import ImageGrab
  File "/usr/lib/python3/dist-packages/PIL/ImageGrab.py", line 22, in <module>
    raise ImportError("ImageGrab is macOS and Windows only")
ImportError: ImageGrab is macOS and Windows only

**Comment by manoflinux** [comment]
[strace.txt](https://github.com/TeaM-TL/FotoKilof/files/8226019/strace.txt)
added an strace if that helps
