### ISSUE TITLE
UnboundLocalError: local variable 'result' referenced before assignment (MacOs)

### ISSUE THREAD

**Issue by frinsen** [TeaM-TL/FotoKilof#123]
I am running MacOs

tried: 

1. python3 -m pip install fotokilof
2. fotokilof

Result:

Traceback (most recent call last):
  File "/opt/homebrew/bin/fotokilof", line 5, in <module>
    from src import __main__
  File "/opt/homebrew/lib/python3.10/site-packages/src/__main__.py", line 2371, in <module>
    GM_or_IM_data = magick.check_magick()
  File "/opt/homebrew/lib/python3.10/site-packages/src/magick.py", line 227, in check_magick
    if check_imagemagick(suffix) is not None:
  File "/opt/homebrew/lib/python3.10/site-packages/src/magick.py", line 268, in check_imagemagick
    return result
UnboundLocalError: local variable 'result' referenced before assignment

**Comment by TeaM-TL** [comment]
Hi
Thanks for bug report. Now I have continuous access to macos and i will solve it in next days

**Comment by TeaM-TL** [comment]
fixed in 3.8.4, I hope that tomorrow I will be able to publish it.
But if you encounter this error it means that you did not install imagemagick, or imagemagics is not in PATH. Please check it

**Comment by frinsen** [comment]
re-adding imagemagick to the path did the job :)
