### ISSUE TITLE
Need to install "requests" to run (windows 11, python 3.11)

### ISSUE THREAD

**Issue by hmu-duc-anh** [TeaM-TL/FotoKilof#173]
I'm using Windows 11, I have python 3.11 and ImageMagick installed.

I installed FotoKilof using
`python -m pip install pywin32 fotokilof`

Then I ran `fotokilof` but nothing showed up.

So I ran
`python -m fotokilof`

It said
```Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\{{MY USERNAME}}\AppData\Local\Programs\Python\Python311\Lib\site-packages\fotokilof\__main__.py", line 62, in <module>
    import check_new_version
  File "C:\Users\{{MY USERNAME}}\AppData\Local\Programs\Python\Python311\Lib\site-packages\fotokilof\check_new_version.py", line 28, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

So I ran
`python -m pip install requests`

It installed `requests`, and then I was able to run `fotokilof`

I only know basic computer stuff so I don't know whether this problem is mine alone. Please have a look, thank you!

**Comment by TeaM-TL** [comment]
many thanks, I will add requests and json into requirements. will be fixed in 4.4.7
